// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fDuAnDibBT3S5CH5aOUc4JlVSAptZMQ',
    appId: '1:309222922349:web:d38067bfb252e549ccc764',
    messagingSenderId: '309222922349',
    projectId: 'swd4-s4',
    authDomain: 'swd4-s4.firebaseapp.com',
    storageBucket: 'swd4-s4.firebasestorage.app',
    measurementId: 'G-397KKLMQTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_mOSHZrywwqgX7vzse006gnMtXyG2K4',
    appId: '1:309222922349:android:e04c7020e98b1d0dccc764',
    messagingSenderId: '309222922349',
    projectId: 'swd4-s4',
    storageBucket: 'swd4-s4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLEfxNPOf-7qzGzzU6bJ6WXP1ZMMKLIFc',
    appId: '1:309222922349:ios:3cbeed3e53b018bbccc764',
    messagingSenderId: '309222922349',
    projectId: 'swd4-s4',
    storageBucket: 'swd4-s4.firebasestorage.app',
    iosBundleId: 'com.example.swd4S4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLEfxNPOf-7qzGzzU6bJ6WXP1ZMMKLIFc',
    appId: '1:309222922349:ios:3cbeed3e53b018bbccc764',
    messagingSenderId: '309222922349',
    projectId: 'swd4-s4',
    storageBucket: 'swd4-s4.firebasestorage.app',
    iosBundleId: 'com.example.swd4S4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6fDuAnDibBT3S5CH5aOUc4JlVSAptZMQ',
    appId: '1:309222922349:web:dab00608dc45c352ccc764',
    messagingSenderId: '309222922349',
    projectId: 'swd4-s4',
    authDomain: 'swd4-s4.firebaseapp.com',
    storageBucket: 'swd4-s4.firebasestorage.app',
    measurementId: 'G-BR4TMGJCD1',
  );
}
